
                         insert into Strasse (Strasse) values ('Rosenstrasse 246');
insert into Strasse (Strasse) values ('Lessingstrasse 111');
insert into Strasse (Strasse) values ('MÃ¶rikestrasse 128a');
insert into Strasse (Strasse) values ('Hauptstrasse 237');
insert into Strasse (Strasse) values ('Geschwister-Scholl-Strasse 32b');
insert into Strasse (Strasse) values ('Seestrasse 31');
insert into Strasse (Strasse) values ('Mozartstrasse 151d');
insert into Strasse (Strasse) values ('Asternweg 138');
insert into Strasse (Strasse) values ('Kirchenweg 58');
insert into Strasse (Strasse) values ('Seestrasse 8');
insert into Strasse (Strasse) values ('Akazienweg 20');
insert into Strasse (Strasse) values ('Stettiner Strasse 167c');
insert into Strasse (Strasse) values ('Markt 92');
insert into Strasse (Strasse) values ('Eichenweg 232');
insert into Strasse (Strasse) values ('Fasanenweg 64');
insert into Strasse (Strasse) values ('Hohe Strasse 289');
insert into Strasse (Strasse) values ('Wiesengrund 296');
insert into Strasse (Strasse) values ('Schulweg 251');
insert into Strasse (Strasse) values ('Eichenweg 45');
insert into Strasse (Strasse) values ('Tulpenstrasse 140d');
insert into Strasse (Strasse) values ('MÃ¼hlstrasse 115');
insert into Strasse (Strasse) values ('Erlenstrasse 59');
insert into Strasse (Strasse) values ('Flurstrasse 96');
insert into Strasse (Strasse) values ('Grenzweg 219');
insert into Strasse (Strasse) values ('Bahnhofstrasse 226');
insert into Strasse (Strasse) values ('Kapellenweg 195');
insert into Strasse (Strasse) values ('Friedensstrasse 92');
insert into Strasse (Strasse) values ('Kreuzweg 136');
insert into Strasse (Strasse) values ('Flurstrasse 257');
insert into Strasse (Strasse) values ('Am Anger 231a');
insert into Strasse (Strasse) values ('Pestalozzistrasse 248');
insert into Strasse (Strasse) values ('Forststrasse 159');
insert into Strasse (Strasse) values ('Neue Strasse 97');
insert into Strasse (Strasse) values ('Kreuzstrasse 93');
insert into Strasse (Strasse) values ('Sonnenweg 152');
insert into Strasse (Strasse) values ('Kiefernweg 162');
insert into Strasse (Strasse) values ('Parkstrasse 240');
insert into Strasse (Strasse) values ('Sonnenstrasse 108');
insert into Strasse (Strasse) values ('Friedrich-Ebert-Strasse 94');
insert into Strasse (Strasse) values ('Pfarrgasse 112');
insert into Strasse (Strasse) values ('Friedrichstrasse 200');
insert into Strasse (Strasse) values ('Tulpenstrasse 132');
insert into Strasse (Strasse) values ('Berliner Strasse 122');
insert into Strasse (Strasse) values ('Beethovenstrasse 229');
insert into Strasse (Strasse) values ('FrÃ¼hlingstrasse 216');
insert into Strasse (Strasse) values ('Industriestrasse 191');
insert into Strasse (Strasse) values ('Waldstrasse 235');
insert into Strasse (Strasse) values ('Brunnenstrasse 81');
insert into Strasse (Strasse) values ('Finkenweg 86');
insert into Strasse (Strasse) values ('Rheinstrasse 268a');
insert into Strasse (Strasse) values ('Am Sportplatz 111');
insert into Strasse (Strasse) values ('Ahornweg 91');
insert into Strasse (Strasse) values ('Lessingstrasse 26');
insert into Strasse (Strasse) values ('Hohlweg 98');
insert into Strasse (Strasse) values ('Tannenstrasse 12');
insert into Strasse (Strasse) values ('Hochstrasse 132');
insert into Strasse (Strasse) values ('Industriestrasse 114');
insert into Strasse (Strasse) values ('Mittelweg 255');
insert into Strasse (Strasse) values ('Lindenstrasse 10');
insert into Strasse (Strasse) values ('Fasanenweg 74');
insert into Strasse (Strasse) values ('Friedhofsweg 40');
insert into Strasse (Strasse) values ('Schlehenweg 16');
insert into Strasse (Strasse) values ('Wiesenstrasse 4d');
insert into Strasse (Strasse) values ('Wiesenstrasse 131b');
insert into Strasse (Strasse) values ('Schulweg 196');
insert into Strasse (Strasse) values ('Pfarrgasse 213');
insert into Strasse (Strasse) values ('Erlenweg 24a');
insert into Strasse (Strasse) values ('Ginsterweg 57');
insert into Strasse (Strasse) values ('Friedrichstrasse 45a');
insert into Strasse (Strasse) values ('Kirchstrasse 2');
insert into Strasse (Strasse) values ('Brunnenweg 159');
insert into Strasse (Strasse) values ('Kirchstrasse 185');
insert into Strasse (Strasse) values ('Bergweg 25');
insert into Strasse (Strasse) values ('Heinrich-Heine-Strasse 242');
insert into Strasse (Strasse) values ('Forststrasse 39');
insert into Strasse (Strasse) values ('Bergweg 8');
insert into Strasse (Strasse) values ('Kurze Strasse 50');
insert into Strasse (Strasse) values ('Neuer Weg 135');
insert into Strasse (Strasse) values ('Gutenbergstrasse 181');
insert into Strasse (Strasse) values ('Robert-Koch-Strasse 272');
insert into Strasse (Strasse) values ('Frankenstrasse 115');
insert into Strasse (Strasse) values ('Tulpenweg 50');
insert into Strasse (Strasse) values ('Daimlerstrasse 262');
insert into Strasse (Strasse) values ('Forststrasse 39');
insert into Strasse (Strasse) values ('Alte Dorfstrasse 186');
insert into Strasse (Strasse) values ('Eichenstrasse 291');
insert into Strasse (Strasse) values ('Parkstrasse 11');
insert into Strasse (Strasse) values ('Schubertstrasse 205');
insert into Strasse (Strasse) values ('Weiherstrasse 161');
insert into Strasse (Strasse) values ('MÃ¼hlgasse 298');
insert into Strasse (Strasse) values ('Erlenstrasse 100');
insert into Strasse (Strasse) values ('Eichenweg 31');
insert into Strasse (Strasse) values ('Lindenweg 5');
insert into Strasse (Strasse) values ('Ulmenweg 97');
insert into Strasse (Strasse) values ('MÃ¼hlenstrasse 223a');
insert into Strasse (Strasse) values ('Lerchenstrasse 216');
insert into Strasse (Strasse) values ('Lindenstrasse 219');
insert into Strasse (Strasse) values ('Amselweg 65');
insert into Strasse (Strasse) values ('Kirchplatz 158');
insert into Strasse (Strasse) values ('Uhlandstrasse 288');
insert into Strasse (Strasse) values ('Drosselweg 136');
insert into Strasse (Strasse) values ('Drosselweg 29');
insert into Strasse (Strasse) values ('Teichstrasse 148c');
insert into Strasse (Strasse) values ('Kolpingstrasse 275');
insert into Strasse (Strasse) values ('Bismarckstrasse 166');
insert into Strasse (Strasse) values ('Robert-Koch-Strasse 170');
insert into Strasse (Strasse) values ('MÃ¼hlenstrasse 263b');
insert into Strasse (Strasse) values ('Klosterstrasse 75');
insert into Strasse (Strasse) values ('BrÃ¼ckenstrasse 299');
insert into Strasse (Strasse) values ('Brunnenstrasse 292a');
insert into Strasse (Strasse) values ('Lange Strasse 67');
insert into Strasse (Strasse) values ('Heckenweg 70');
insert into Strasse (Strasse) values ('Finkenstrasse 219c');
insert into Strasse (Strasse) values ('MÃ¶rikestrasse 99');
insert into Strasse (Strasse) values ('MÃ¶rikestrasse 195');
insert into Strasse (Strasse) values ('Eichenweg 275');
insert into Strasse (Strasse) values ('Haydnstrasse 132');
insert into Strasse (Strasse) values ('Beethovenstrasse 215');
insert into Strasse (Strasse) values ('Dahlienweg 44');
insert into Strasse (Strasse) values ('MÃ¼hlstrasse 277');
insert into Strasse (Strasse) values ('Flurstrasse 190');
insert into Strasse (Strasse) values ('Seestrasse 6');
insert into Strasse (Strasse) values ('Grabenstrasse 42');
insert into Strasse (Strasse) values ('HÃ¶henweg 172');
insert into Strasse (Strasse) values ('LÃ¤rchenweg 25');
insert into Strasse (Strasse) values ('Heinrich-Heine-Strasse 49');
insert into Strasse (Strasse) values ('Robert-Bosch-Strasse 260c');
insert into Strasse (Strasse) values ('Fichtenstrasse 123');
insert into Strasse (Strasse) values ('Luisenstrasse 163');
insert into Strasse (Strasse) values ('Eichenstrasse 286');
insert into Strasse (Strasse) values ('Fichtenstrasse 228');
insert into Strasse (Strasse) values ('Siedlung 277');
insert into Strasse (Strasse) values ('Marktplatz 8');
insert into Strasse (Strasse) values ('Ludwigstrasse 40');
insert into Strasse (Strasse) values ('Ahornstrasse 209');
insert into Strasse (Strasse) values ('Blumenstrasse 216');
insert into Strasse (Strasse) values ('Marienstrasse 236');
insert into Strasse (Strasse) values ('Wiesenweg 76');
insert into Strasse (Strasse) values ('Friedrichstrasse 151');
insert into Strasse (Strasse) values ('Stettiner Strasse 60');
insert into Strasse (Strasse) values ('Rathausstrasse 262');
insert into Strasse (Strasse) values ('Marktstrasse 267');
insert into Strasse (Strasse) values ('Blumenstrasse 41');
insert into Strasse (Strasse) values ('Teichstrasse 227');
insert into Strasse (Strasse) values ('Falkenweg 154');
insert into Strasse (Strasse) values ('Klosterstrasse 180');
insert into Strasse (Strasse) values ('Finkenweg 157');
insert into Strasse (Strasse) values ('Ginsterweg 78');
insert into Strasse (Strasse) values ('Hohlweg 70c');
insert into Strasse (Strasse) values ('Schwarzer Weg 69');
insert into Strasse (Strasse) values ('Mozartstrasse 215a');
insert into Strasse (Strasse) values ('Raiffeisenstrasse 173');
insert into Strasse (Strasse) values ('Lindenstrasse 29');
insert into Strasse (Strasse) values ('MÃ¼hlgasse 113');
insert into Strasse (Strasse) values ('Stettiner Strasse 200');
insert into Strasse (Strasse) values ('Breslauer Strasse 38');
insert into Strasse (Strasse) values ('Karlstrasse 272c');
insert into Strasse (Strasse) values ('FrÃ¼hlingstrasse 64');
insert into Strasse (Strasse) values ('GrÃ¼ner Weg 290');
insert into Strasse (Strasse) values ('Grenzweg 158');
insert into Strasse (Strasse) values ('Siedlung 42');
insert into Strasse (Strasse) values ('Schulstrasse 174');
insert into Strasse (Strasse) values ('Kirchgasse 37');
insert into Strasse (Strasse) values ('Siemensstrasse 116');
insert into Strasse (Strasse) values ('Neue Strasse 241');
insert into Strasse (Strasse) values ('Birkenweg 195');
insert into Strasse (Strasse) values ('Schillerstrasse 42');
insert into Strasse (Strasse) values ('Industriestrasse 180');
insert into Strasse (Strasse) values ('Wiesenstrasse 1');
insert into Strasse (Strasse) values ('Fasanenweg 207');
insert into Strasse (Strasse) values ('Grenzweg 58');
insert into Strasse (Strasse) values ('Am Friedhof 241');
insert into Strasse (Strasse) values ('Klosterstrasse 56');
insert into Strasse (Strasse) values ('Eichendorffstrasse 108');
insert into Strasse (Strasse) values ('Schillerstrasse 228');
insert into Strasse (Strasse) values ('Falkenweg 73');
insert into Strasse (Strasse) values ('Kirchstrasse 86');
insert into Strasse (Strasse) values ('Hauptstrasse 144');
insert into Strasse (Strasse) values ('Tulpenstrasse 37');
insert into Strasse (Strasse) values ('Schlossstrasse 220');
insert into Strasse (Strasse) values ('Robert-Bosch-Strasse 281');
insert into Strasse (Strasse) values ('Brunnenweg 210');
insert into Strasse (Strasse) values ('Siemensstrasse 220');
insert into Strasse (Strasse) values ('Uhlandstrasse 140');
insert into Strasse (Strasse) values ('MÃ¼hlenweg 119c');
insert into Strasse (Strasse) values ('Stettiner Strasse 14');
insert into Strasse (Strasse) values ('Haydnstrasse 108c');
insert into Strasse (Strasse) values ('Brunnenweg 41');
insert into Strasse (Strasse) values ('Im Winkel 288');
insert into Strasse (Strasse) values ('HÃ¶henweg 171');
insert into Strasse (Strasse) values ('Mozartstrasse 133');
insert into Strasse (Strasse) values ('Geschwister-Scholl-Strasse 224');
insert into Strasse (Strasse) values ('Pfarrgasse 56d');
insert into Strasse (Strasse) values ('KÃ¶nigsberger Strasse 190');
insert into Strasse (Strasse) values ('Buchenweg 256');
insert into Strasse (Strasse) values ('Lessingstrasse 174');
insert into Strasse (Strasse) values ('Luisenstrasse 269');
insert into Strasse (Strasse) values ('Oststrasse 175');
insert into Strasse (Strasse) values ('MÃ¶rikestrasse 19');
insert into Strasse (Strasse) values ('Nelkenstrasse 288');
insert into Strasse (Strasse) values ('Brunnenstrasse 179');
insert into Strasse (Strasse) values ('Brunnenweg 238');
insert into Strasse (Strasse) values ('Steinweg 94c');
insert into Strasse (Strasse) values ('Berliner Strasse 279');
insert into Strasse (Strasse) values ('Friedrichstrasse 81');
insert into Strasse (Strasse) values ('Lilienweg 189');
insert into Strasse (Strasse) values ('Blumenweg 155');
insert into Strasse (Strasse) values ('Breslauer Strasse 85');

