insert into Ort (Ort) values ('Heringen (Werra)');
insert into Ort (Ort) values ('Frauenstein');
insert into Ort (Ort) values ('Oppenau');
insert into Ort (Ort) values ('Obertshausen');
insert into Ort (Ort) values ('Geisa');
insert into Ort (Ort) values ('Heusenstamm');
insert into Ort (Ort) values ('Trostberg');
insert into Ort (Ort) values ('Geithain');
insert into Ort (Ort) values ('Bad DÃ¼rkheim');
insert into Ort (Ort) values ('Artern/Unstrut');
insert into Ort (Ort) values ('Neustadt a.d.Donau');
insert into Ort (Ort) values ('Glauchau');
insert into Ort (Ort) values ('GeorgsmarienhÃ¼tte');
insert into Ort (Ort) values ('Berga/Elster');
insert into Ort (Ort) values ('Naunhof');
insert into Ort (Ort) values ('LÃ¶ningen');
insert into Ort (Ort) values ('Bad Liebenstein');
insert into Ort (Ort) values ('Landau a.d.Isar');
insert into Ort (Ort) values ('VohenstrauÃŸ');
insert into Ort (Ort) values ('Bredstedt');
insert into Ort (Ort) values ('Bad Freienwalde (Oder)');
insert into Ort (Ort) values ('Merkendorf');
insert into Ort (Ort) values ('DÃ¼lmen');
insert into Ort (Ort) values ('Bopfingen');
insert into Ort (Ort) values ('Eisenach');
insert into Ort (Ort) values ('IbbenbÃ¼ren');
insert into Ort (Ort) values ('Kirchheim unter Teck');
insert into Ort (Ort) values ('Kirtorf');
insert into Ort (Ort) values ('Rosenthal');
insert into Ort (Ort) values ('FÃ¼rstenfeldbruck');
insert into Ort (Ort) values ('Bad Wilsnack');
insert into Ort (Ort) values ('Heidenau');
insert into Ort (Ort) values ('Burscheid');
insert into Ort (Ort) values ('Ahaus');
insert into Ort (Ort) values ('SchkÃ¶len');
insert into Ort (Ort) values ('Holzminden');
insert into Ort (Ort) values ('Landau in der Pfalz');
insert into Ort (Ort) values ('Wurzbach');
insert into Ort (Ort) values ('Netphen');
insert into Ort (Ort) values ('SchwabmÃ¼nchen');
insert into Ort (Ort) values ('Straubing');
insert into Ort (Ort) values ('Harburg (Schwaben)');
insert into Ort (Ort) values ('LÃ¶bau');
insert into Ort (Ort) values ('Seelze');
insert into Ort (Ort) values ('TÃ¼bingen');
insert into Ort (Ort) values ('Schrobenhausen');
insert into Ort (Ort) values ('Aschersleben');
insert into Ort (Ort) values ('Baunatal');
insert into Ort (Ort) values ('Oberhof');
insert into Ort (Ort) values ('Alzenau');
insert into Ort (Ort) values ('Schwetzingen');
insert into Ort (Ort) values ('HÃ¼ckelhoven');
insert into Ort (Ort) values ('Wiesloch');
insert into Ort (Ort) values ('Heimsheim');
insert into Ort (Ort) values ('Bergisch Gladbach');
insert into Ort (Ort) values ('Obertshausen');
insert into Ort (Ort) values ('Dettelbach');
insert into Ort (Ort) values ('MÃ¼geln');
insert into Ort (Ort) values ('Kirtorf');
insert into Ort (Ort) values ('Pinneberg');
insert into Ort (Ort) values ('DonauwÃ¶rth');
insert into Ort (Ort) values ('Monheim am Rhein');
insert into Ort (Ort) values ('Solms');
insert into Ort (Ort) values ('BremervÃ¶rde');
insert into Ort (Ort) values ('Lorch');
insert into Ort (Ort) values ('Bonndorf im Schwarzwald');
insert into Ort (Ort) values ('Herford');
insert into Ort (Ort) values ('Brackenheim');
insert into Ort (Ort) values ('WÃ¶rth am Rhein');
insert into Ort (Ort) values ('Bad Pyrmont');
insert into Ort (Ort) values ('Bretten');
insert into Ort (Ort) values ('Hagen');
insert into Ort (Ort) values ('Rodgau');
insert into Ort (Ort) values ('Heidenau');
insert into Ort (Ort) values ('Kulmbach');
insert into Ort (Ort) values ('Senden');
insert into Ort (Ort) values ('Taunusstein');
insert into Ort (Ort) values ('Wiehl');
insert into Ort (Ort) values ('Pottenstein');
insert into Ort (Ort) values ('MÃ¼nster');
insert into Ort (Ort) values ('Woldegk');
insert into Ort (Ort) values ('Coswig (Anhalt)');
insert into Ort (Ort) values ('Lehrte');
insert into Ort (Ort) values ('Ebermannstadt');
insert into Ort (Ort) values ('Meppen');
insert into Ort (Ort) values ('Themar');
insert into Ort (Ort) values ('RÃ¼sselsheim');
insert into Ort (Ort) values ('FÃ¼rstenwalde/Spree');
insert into Ort (Ort) values ('Schrozberg');
insert into Ort (Ort) values ('Pressath');
insert into Ort (Ort) values ('Eggenfelden');
insert into Ort (Ort) values ('Cuxhaven');
insert into Ort (Ort) values ('Dillingen/ Saar');
insert into Ort (Ort) values ('Welzow');
insert into Ort (Ort) values ('Paderborn');
insert into Ort (Ort) values ('Lehesten');
insert into Ort (Ort) values ('NÃ¼rnberg');
insert into Ort (Ort) values ('Bad Langensalza');
insert into Ort (Ort) values ('Burgkunstadt');
insert into Ort (Ort) values ('Weilheim an der Teck');
insert into Ort (Ort) values ('GroÃŸbottwar');
insert into Ort (Ort) values ('Freinsheim');
insert into Ort (Ort) values ('Schongau');
insert into Ort (Ort) values ('Schweinfurt');
insert into Ort (Ort) values ('MÃ¼nchen');
insert into Ort (Ort) values ('ZiegenrÃ¼ck');
insert into Ort (Ort) values ('Apolda');
insert into Ort (Ort) values ('St. Georgen im Schwarzwald');
insert into Ort (Ort) values ('Pausa-MÃ¼hltroff');
insert into Ort (Ort) values ('VisselhÃ¶vede');
insert into Ort (Ort) values ('BÃ¼hl');
insert into Ort (Ort) values ('Hornbach');
insert into Ort (Ort) values ('Renchen');
insert into Ort (Ort) values ('Buchen (Odenwald)');
insert into Ort (Ort) values ('Weil der Stadt');
insert into Ort (Ort) values ('Berka/Werra');
insert into Ort (Ort) values ('Sigmaringen');
insert into Ort (Ort) values ('Wesel');
insert into Ort (Ort) values ('Altentreptow');
insert into Ort (Ort) values ('Plauen');
insert into Ort (Ort) values ('Naumburg');
insert into Ort (Ort) values ('Herzogenrath');
insert into Ort (Ort) values ('Demmin');
insert into Ort (Ort) values ('Wetter (Ruhr)');
insert into Ort (Ort) values ('Velen');
insert into Ort (Ort) values ('Wildenfels');
insert into Ort (Ort) values ('Dreieich');
insert into Ort (Ort) values ('Andernach');
insert into Ort (Ort) values ('Laatzen');
insert into Ort (Ort) values ('Bernkastel-Kues');
insert into Ort (Ort) values ('Auerbach i.d.OPf.');
insert into Ort (Ort) values ('Burg');
insert into Ort (Ort) values ('Selb');
insert into Ort (Ort) values ('FÃ¼rth');
insert into Ort (Ort) values ('Bad Griesbach i.Rottal');
insert into Ort (Ort) values ('Halle (Westf.)');
insert into Ort (Ort) values ('Wittenberge');
insert into Ort (Ort) values ('Raunheim');
insert into Ort (Ort) values ('Bleicherode');
insert into Ort (Ort) values ('Zarrentin am Schaalsee');
insert into Ort (Ort) values ('Solingen, Klingenstadt');
insert into Ort (Ort) values ('Bassum');
insert into Ort (Ort) values ('GÃ¼strow');
insert into Ort (Ort) values ('Freiberg am Neckar');
insert into Ort (Ort) values ('Radebeul');
insert into Ort (Ort) values ('LÃ¶ÃŸnitz');
insert into Ort (Ort) values ('Neuburg a.d.Donau');
insert into Ort (Ort) values ('Freinsheim');
insert into Ort (Ort) values ('Ober-Ramstadt');
insert into Ort (Ort) values ('Emmerich am Rhein');
insert into Ort (Ort) values ('Esslingen am Neckar');
insert into Ort (Ort) values ('Lunzenau');
insert into Ort (Ort) values ('Freyung');
insert into Ort (Ort) values ('Andernach');
insert into Ort (Ort) values ('Gernsbach');
insert into Ort (Ort) values ('ZwÃ¶nitz');
insert into Ort (Ort) values ('Bad Laasphe');
insert into Ort (Ort) values ('Hessisch Oldendorf');
insert into Ort (Ort) values ('St. Georgen im Schwarzwald');
insert into Ort (Ort) values ('Geseke');
insert into Ort (Ort) values ('MÃ¶nchengladbach');
insert into Ort (Ort) values ('Baumholder');
insert into Ort (Ort) values ('Hallstadt');
insert into Ort (Ort) values ('Viersen');
insert into Ort (Ort) values ('Bretten');
insert into Ort (Ort) values ('Roding');
insert into Ort (Ort) values ('Helmbrechts');
insert into Ort (Ort) values ('Kirchen (Sieg)');
insert into Ort (Ort) values ('Bad Kreuznach');
insert into Ort (Ort) values ('Neuhaus am Rennweg');
insert into Ort (Ort) values ('Gaggenau');
insert into Ort (Ort) values ('Baesweiler');
insert into Ort (Ort) values ('Bad Muskau');
insert into Ort (Ort) values ('Lebus');
insert into Ort (Ort) values ('Drebkau');
insert into Ort (Ort) values ('Simmern/ HunsrÃ¼ck');
insert into Ort (Ort) values ('Hungen');
insert into Ort (Ort) values ('Saalburg-Ebersdorf');
insert into Ort (Ort) values ('Marburg');
insert into Ort (Ort) values ('MÃ¼hlhausen/ThÃ¼ringen');
insert into Ort (Ort) values ('Rheinberg');
insert into Ort (Ort) values ('Diepholz');
insert into Ort (Ort) values ('Renchen');
insert into Ort (Ort) values ('BÃ¤rnau');
insert into Ort (Ort) values ('Staufenberg');
insert into Ort (Ort) values ('Doberlug-Kirchhain');
insert into Ort (Ort) values ('Wittstock/Dosse');
insert into Ort (Ort) values ('Tornesch');
insert into Ort (Ort) values ('Marl');
insert into Ort (Ort) values ('HÃ¼nfeld, Konrad-Zuse-Stadt');
insert into Ort (Ort) values ('Sehnde');
insert into Ort (Ort) values ('Rathenow');
insert into Ort (Ort) values ('Laufenburg (Baden)');
insert into Ort (Ort) values ('Clingen');
insert into Ort (Ort) values ('Franzburg');
insert into Ort (Ort) values ('Wilkau-HaÃŸlau');
insert into Ort (Ort) values ('Ahlen');
insert into Ort (Ort) values ('Straelen');
insert into Ort (Ort) values ('Marktbreit');
insert into Ort (Ort) values ('Horb am Neckar');
insert into Ort (Ort) values ('Rahden');
insert into Ort (Ort) values ('Oderberg');
insert into Ort (Ort) values ('Wyk auf FÃ¶hr');
insert into Ort (Ort) values ('Abenberg');
insert into Ort (Ort) values ('Kronberg im Taunus');
insert into Ort (Ort) values ('Heubach');
insert into Ort (Ort) values ('EisenhÃ¼ttenstadt');
insert into Ort (Ort) values ('Kamen');


