CREATE TABLE Mail(
	Mail_OID int NOT NULL,
	Notiz_OID int,
	Person_OID int,
	Mailnachricht varchar(256)
);

CREATE TABLE Notizen(
	Notizen_OID int NOT NULL,
	Person_OID int,
	Text varchar(256),
	Mail_OID int
);

CREATE TABLE Person(
	Person_OID int NOT NULL,
	Nachname varchar(20),
	Mail_OID int
);

ALTER TABLE Mail ADD CONSTRAINT PK_Mail PRIMARY KEY(Mail_OID);
ALTER TABLE Notizen ADD CONSTRAINT PK_Notizen PRIMARY KEY(Notizen_OID);
ALTER TABLE Person ADD CONSTRAINT PK_Person PRIMARY KEY(Person_OID);

ALTER TABLE Mail ADD CONSTRAINT FK_Mail_0 FOREIGN KEY(Person_OID) REFERENCES Person(Person_OID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Mail ADD CONSTRAINT FK_Mail_1 FOREIGN KEY(Notiz_OID) REFERENCES Notizen(Notizen_OID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Notizen ADD CONSTRAINT FK_Notizen_0 FOREIGN KEY(Person_OID) REFERENCES Person(Person_OID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Notizen ADD CONSTRAINT FK_Notizen_1 FOREIGN KEY(Mail_OID) REFERENCES Mail(Mail_OID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Person ADD CONSTRAINT FK_Person_0 FOREIGN KEY(Mail_OID) REFERENCES Mail(Mail_OID) ON DELETE NO ACTION ON UPDATE NO ACTION;
