CREATE TABLE Buch(
	Buch_OID int NOT NULL,
	Titel varchar(20),
	Verfasser varchar(20)
);

CREATE TABLE Vormerkt(
	Lerser_OID int NOT NULL,
	Buch_OID int NOT NULL,
	VormDat date
);

CREATE TABLE Leser(
	Leser_OID int NOT NULL,
	Nachname varchar(20),
	Mail varchar(20)
);

CREATE TABLE Mahnung(
	Mahnung_OID int NOT NULL,
	Leser_OID int NOT NULL,
	Buch_OID int NOT NULL,
	Ex_ID int NOT NULL,
	Datum date,
	Betrag decimal(6,2)
);

CREATE TABLE Ausleihe(
	Buch_OID int NOT NULL,
	ExID int NOT NULL,
	Leser_OID int,
	LNr int,
	ADat date,
	RDat date
);

CREATE TABLE Exemplar(
	Buch_OID int NOT NULL,
	ExID int NOT NULL,
	AnschDat date
);

ALTER TABLE Buch ADD CONSTRAINT PK_Buch PRIMARY KEY(Buch_OID);
ALTER TABLE Vormerkt ADD CONSTRAINT PK_Vormerkt PRIMARY KEY(Lerser_OID,Buch_OID);
ALTER TABLE Leser ADD CONSTRAINT PK_Leser PRIMARY KEY(Leser_OID);
ALTER TABLE Mahnung ADD CONSTRAINT PK_Mahnung PRIMARY KEY(Mahnung_OID);
ALTER TABLE Ausleihe ADD CONSTRAINT PK_Ausleihe PRIMARY KEY(Buch_OID,ExID);
ALTER TABLE Exemplar ADD CONSTRAINT PK_Exemplar PRIMARY KEY(ExID,Buch_OID);

ALTER TABLE Vormerkt ADD CONSTRAINT FK_Vormerkt_0 FOREIGN KEY(Buch_OID) REFERENCES Buch(Buch_OID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Vormerkt ADD CONSTRAINT FK_Vormerkt_1 FOREIGN KEY(Lerser_OID) REFERENCES Leser(Leser_OID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Mahnung ADD CONSTRAINT FK_Mahnung_0 FOREIGN KEY(Leser_OID) REFERENCES Leser(Leser_OID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Ausleihe ADD CONSTRAINT FK_Ausleihe_0 FOREIGN KEY(Leser_OID) REFERENCES Leser(Leser_OID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Exemplar ADD CONSTRAINT FK_Exemplar_0 FOREIGN KEY(Buch_OID) REFERENCES Buch(Buch_OID) ON DELETE CASCADE ON UPDATE CASCADE;
